name: CShift Organization Security

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security:
    uses: cshift-tech/public-actions/.github/workflows/ts-app-security.yml@main
  dependency-review:
    uses: cshift-tech/public-actions/.github/workflows/dependency-review.yml@main
